### ISSUE TITLE
player achievement announcement spam

### ISSUE THREAD

**Issue by mentisFlumine** [CarsonKompon/pizza_clicker#4]
some people could hack game data to obtain all achievements at once and resulting in lag spike for anyone with weak pc (including the initiator of this)

![изображение](https://github.com/CarsonKompon/pizza_clicker/assets/139696679/c4338ee4-7f80-4f1f-99d5-a96920e4e039)

**Comment by CarsonKompon** [comment]
Fixed by https://github.com/CarsonKompon/pizza_clicker/pull/11
