### ISSUE TITLE
chatbox&chatentry overflow is not working properly

### ISSUE THREAD

**Issue by mentisFlumine** [CarsonKompon/pizza_clicker#5]
![изображение](https://github.com/CarsonKompon/pizza_clicker/assets/139696679/1e386698-4641-4df5-966a-f266631aab85)

**Comment by CarsonKompon** [comment]
This is partially fixed by https://github.com/CarsonKompon/pizza_clicker/pull/10. I won't close this issue just yet however.

**Comment by CarsonKompon** [comment]
Should be fixed by https://github.com/CarsonKompon/pizza_clicker/pull/13
