### ISSUE TITLE
Wrong descriptions for some upgrades

### ISSUE THREAD

**Issue by Taizunz** [CarsonKompon/pizza_clicker#7]
Some upgrades have the wrong descriptions.
One example: 
![image](https://github.com/CarsonKompon/pizza_clicker/assets/15648000/95e846c9-fc02-49d6-8e3b-b3a0fba14a3b)

**Comment by CarsonKompon** [comment]
Fixed by https://github.com/CarsonKompon/pizza_clicker/pull/9
